# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio     
      - name: Generate build number
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.github_token}}
      - name: Get current time
        uses: 1466587594/get-current-time@v1
        id: current-time
        with:
          format: DDMMYYYY-HHmmss
          utcOffset: "+02:00"
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: echo $TIME $F_TIME
      - name: Print new build number
        run: | 
          echo "Build number is $BUILD_NUMBER"
          echo ::set-env name=RELEASE_VERSION::v1.0.${BUILD_NUMBER}
          echo ::set-env name=SIMPLEAE_FIRMWARE_NAME::SimpleAE_1.0.${BUILD_NUMBER}_${{ steps.current-time.outputs.formattedTime }}.bin
      - name: Run PlatformIO for SimpleAE 
          cd ./SOFT_ARDUINO/
          platformio run -e nanoatmega328
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file:  ./SOFT_ARDUINO/.pio/build/nanoatmega328/firmware.bin
          tag: ${{ env.RELEASE_VERSION }}
          asset_name: ${{ env.SIMPLEAE_FIRMWARE_NAME }}
          overwrite: true
          body: "This is my release text"
