# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v1
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio   
            
      - name: Generate build number
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{secrets.github_token}}
      
      - name: Get current time
        uses: 1466587594/get-current-time@v1
        id: current-time
        with:
          format: DDMMYYYY-HHmmss
          utcOffset: "+02:00"
      
      - name: Set variables
        id: env
        run: |
          echo '::set-output name=TIME::${{ steps.current-time.outputs.time }}'
          echo '::set-output name=BUILD_NUMBER::${{env.BUILD_NUMBER}}'
          echo '::set-output name=RELEASE_VERSION::v1.0.${{env.BUILD_NUMBER}}'
          echo '::set-output name=SIMPLEAE_FIRMWARE_NAME::SimpleAE_1.0.${{env.BUILD_NUMBER}}_${{ steps.current-time.outputs.formattedTime }}.hex'
          echo '::set-output name=SIMPLEAE_EXE_NAME::SimpleAE_1.0.${{env.BUILD_NUMBER}}_${{ steps.current-time.outputs.formattedTime }}.exe'
          
      - name: Print new build number
        run: |
          echo ${{steps.env.outputs.TIME}}
          echo ${{steps.env.outputs.BUILD_NUMBER}}
          echo ${{steps.env.outputs.RELEASE_VERSION}}
          echo ${{steps.env.outputs.SIMPLEAE_FIRMWARE_NAME}}
          echo ${{steps.env.outputs.SIMPLEAE_EXE_NAME}}
      
      - name: Run PlatformIO for SimpleAE 
        run: |
          cd ./SOFT_ARDUINO/
          platformio run -e nanoatmega328
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file:  ./SOFT_ARDUINO/.pio/build/nanoatmega328/firmware.hex
          tag: ${{steps.env.outputs.RELEASE_VERSION}}
          asset_name: ${{steps.env.outputs.SIMPLEAE_FIRMWARE_NAME}}
          overwrite: true
          body: "This is my release text"
       
      - name: Bump Version
        run: |
          cd ./SOFT_PC/
          npm version 1.0.${{steps.env.outputs.BUILD_NUMBER}}
          
      - name: Run npm install for SimpleAE 
        run: |
          cd ./SOFT_PC/
          npm install
          
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          release: true
          app_root: ./SOFT_PC/
          package_root: ./SOFT_PC/
          github_token: ${{ secrets.github_token }}
